sudo: requierd
services:
  - docker

before_install:
  - docker build -t gadshaked/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gadshaked/docker-react npm run test -- --coverage